#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute

article_list:
    path: /
    controller: App\Controller\IndexController::home
article_save:
    path: /article/save
    controller: App\Controller\IndexController::save
new_article:
    path: /article/new
    controller: App\Controller\IndexController::new
    methods: [POST]
edit_article:
    path: /article/edit/{id}
    controller: App\Controller\IndexController::edit
    methods: [POST]
article_show:
    path: /article/{id}
    controller: App\Controller\IndexController::show
delete_article:
  path: /article/delete/{id}
  controller: App\Controller\ArticleController::delete
  methods: [DELETE]